### ISSUE TITLE
ArgumentType.INTEGER doesn't support negative values // Flags do consume and error negative numbers & stack trace gets printed

### ISSUE THREAD

**Issue by AlphaYui** [Einsyui/BuildUtils#2]
ArgumentType.INTEGER seems not to support negative values. It has been recognized using the command "/bu set <groupname> <x> <y> <z> <world>". As soon as x, y or z get assigned a negative value, an ArgumentSyntaxException is thrown, even if a syntax like "/bu set x=3 y=-5 z=-8 group=test" is used. The following stacktrace is shown in the server console:
![argument_syntax_exception_stacktrace](https://cloud.githubusercontent.com/assets/5251203/6218849/f6afc2be-b622-11e4-993f-4109fd422a28.png)

Another issue is that there are problems with catching said exceptions. Although a try-catch statement has been placed around the statement which must cause the exception (commands.handleCommand(...) in Main.java) it still doesn't get caught and causes massive distraction in the server logs by adding a quite long exception stacktrace to it, everytime a command doesn't have the right syntax. This also occurs, when the brackets of a bracketed ArgumentType are forgotten.

**Comment by marzipankaiser** [comment]
The StackTrace is printed for debugging purposes. See CommandLibrary.java, line 32.
I will test negative Integers again, though they worked last time... !?

**Comment by marzipankaiser** [comment]
Can't reproduce here, exactly the same (but with world=world) in Console...

```
>bu set x=3 y=-5 z=-8 group=test world=world
[09:52:39 INFO]: Successfully pushed position [world|3|-5|-8] to stack 'test'!
```

**Comment by marzipankaiser** [comment]
Ah, I think I found the error: 
It tries to parse it as a flag when it starts with +/-...
Will fix soon.

**Comment by marzipankaiser** [comment]
This seems to fix it.
(commit 22dc46b1225c85a834866380c61aa1c3f2081a66)

**Comment by marzipankaiser** [comment]
Will remove the e.printStackTrace() soon...

**Comment by marzipankaiser** [comment]
No stack trace now.
